config/routes.rb
Rails.application.routes.draw do
  root to: 'superheros#index'

  resources :superheros
  resources :cities
end

app/models/city.rb
class City < ActiveRecord::Base
  validates :name, :presence => true
  has_many :superheros
end

app/models/superhero.rb
class Superhero < ActiveRecord::Base
  belongs_to :city
  validates :name, :presence => true
  validates :superpower, :presence => true
  validates :archenemy, :presence => true
  default_scope { order('superpower') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params)
    if @city.save
      flash[:notice] = "City added."
      redirect_to cities_path
    else
      render 'new'
    end
  end

  def show
    @city = City.find(params[:id])
  end

  def edit
    @city = City.find(params[:id])
  end

  def update
    @city = City.find(params[:id])
    if @city.update(city_params)
      flash[:notice] = "City updated."
      redirect_to city_path
    else
      render 'edit'
    end
  end

  def destroy
    @city = City.find(params[:id])
    @city.destroy
    flash[:notice] = "City deleted."
    redirect_to cities_path
  end

private
  def city_params
    params.require(:city).permit(:name)
  end
end

app/controllers/superheros_controller.rb
class SuperherosController < ApplicationController
  def index
    @cities = City.all
    @superheros = Superhero.order(city_id: :asc, superpower: :asc)
    if params[:search]
      @query = params[:search]
      @results = Superhero.basic_search(@query)
      render :search_results
    end
  end

  def new
    @superhero = Superhero.new
  end

  def create
    # @city = City.find(params[:superhero][:city_id])
    @superhero = Superhero.new(superhero_params)
    if @superhero.save
      flash[:notice] = "Superhero added."
      redirect_to superheros_path
    else
      render 'new'
    end
  end

  def show
    @superhero = Superhero.find(params[:id])
  end

  def edit
    @superhero = Superhero.find(params[:id])
  end

  def update
    @superhero = Superhero.find(params[:id])
    if @superhero.update(superhero_params)
      flash[:notice] = "Superhero updated."
      redirect_to superhero_path
    else
      render 'edit'
    end
  end

  def destroy
    @superhero = Superhero.find(params[:id])
    @superhero.destroy
    flash[:notice] = "Superhero deleted."
    redirect_to superheros_path
  end

private
  def superhero_params
    params.require(:superhero).permit(:name, :city_id, :superpower, :archenemy)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cities/_form.html.erb
<%= render("layouts/errors", :object => @city) %>

<%= form_for(@city) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/cities/index.html.erb
<%= content_for(:title, "Cities | National Superhero Registry") %>

<h1>National Superhero Registry</h1>
<h2>Cities</h2>

<ul>
  <% @cities.each do |city| %>
    <li><a href="/cities/<%= city.id %>"><%= city.name %></a></li>
  <% end %>
</ul>

<%= link_to "Add A New City", new_city_path, :class=> "btn btn-default" %><br><br>

<%= link_to "Return To Cities Listings", cities_path %><br><br>
<%= link_to "Return To Superhero Listings", superheros_path %>

app/views/cities/new.html.erb
<%= content_for(:title, "New | National Superhero Registry") %>

<h1>New City</h1>

<%= render('form') %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:alert] %>
<%= flash[:notice] %>

<%= yield %>

</body>
</html>

app/views/superheros/_form.html.erb
<%= render("layouts/errors", :object => @superhero) %>

<%= form_for(@superhero) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
  <%= f.collection_select :city_id, City.all, :id, :name %>
  </div>
  <div class="form-group">
    <%= f.label :superpower %>
    <%= f.text_field :superpower %>
  </div>
  <div class="form-group">
    <%= f.label :archenemy %>
    <%= f.text_field :archenemy %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/superheros/destroy.html.erb
<%= content_for(:title, "Deleted | National Superhero Registry") %>

<h1>Superhero deleted!</h1>

app/views/superheros/edit.html.erb
<%= content_for(:title, "Edit | National Superhero Registry") %>

<h1>Edit superhero</h1>

<%= render('form') %>

<%= link_to "Return to superhero listings", superheros_path, :class=> "btn btn-default" %>

app/views/superheros/index.html.erb
<%= content_for(:title, "Superheros | National Superhero Registry") %>

<h1>National Superhero Registry</h1>
<h2>Superheroes</h2>

<ul>
  <% @cities.each do |city| %>
   <li><%= city.name %>
      <ul>
        <% city.superheros.each do |superhero| %>
          <li><a href="/superheros/<%= superhero.id %>"><%= superhero.name %></a></li><%= superhero.superpower %>
        <% end %>
      </ul>
     </li>
  <% end %>
</ul>

<%= form_tag '/superheros', :method => 'get' do %>
  <%= label_tag :search, 'Search for a superhero by name:' %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', :class => 'btn btn-primary' %>
<% end %><br>

<%= link_to "Add A New City", new_city_path, :class=> 'btn btn-default' %><br><br>
<%= link_to "Add A New Superhero", new_superhero_path, :class=> "btn btn-default" %>

app/views/superheros/new.html.erb
<%= content_for(:title, "New | National Superhero Registry") %>

<h1>New Superhero</h1>

<%= render('form') %><br>

<%= link_to "Return To Superhero Listings", superheros_path, :class=> "btn btn-default" %>

app/views/superheros/search_results.html.erb
<% provide :title, "Superheroes containing '#{@query}'" %>

<h1><%= yield :title %></h1>

<% if @results.any? %>
  <ul>
    <% @results.each do |superhero| %>
      <li><%= link_to superhero.name, superhero %></li>
    <% end %>
  </ul>
<% else %>
  <p>No results found.</p>
<% end %>

app/views/superheros/show.html.erb
<%= content_for(:title, "View | National Superhero Registry") %>

<h1>View Superheroes</h1>
<h2>Name: <%= @superhero.name %></h2>
<h4>City: <%= @superhero.city.name %></h4>
<h4>Superpower: <%= @superhero.superpower %></h4>
<h4>Archenemy: <%= @superhero.archenemy %></h4>

<p><%= link_to "Edit", edit_superhero_path(@superhero), :class => "btn btn-default" %></p>
<p><%= link_to "Delete", superhero_path(@superhero),
                         :confirm => "You sure?",
                         :method => "delete",
                         :class => "btn btn-danger" %></p>
<%= link_to "Return To Superhero Listings", superheros_path, :class=> "btn btn-default" %>

app/views/superheros/success.html.erb
<%= content_for(:title, "Saved | National Superhero Registry") %>

<h1>Superhero saved!</h1>